sudo: false
language: java
before_script:
    - lein deps
    - yarn install
jobs:
    include:
        - stage: "Lint"
          script: yarn run lint
          script: yarn run flow

        - stage: "Test"
          install: skip
          script:
              - yarn run test-karma
              - yarn run test-unit

cache:
    directories:
        - node_modules
        - ~/.yarn
        - ~/.yarn-cache
