sudo: false
language: java
before_script:
    - lein deps
    - yarn install
jobs:
    include:
        - stage: "Lint"
          name: "JS Lint"
          script: yarn run lint
        - script: yarn run flow
          name: "JSFlow"
        - script: lein eastwood
          name: "Clojure Eastwood"
        - script: lein bikeshed
          name: "Clojure Bikeshed"

        - stage: "Test"
          install: skip
          script: yarn run test-karma
          name: "JS Karma"
        - script: yarn run test-unit
          name: "JS Unit"

cache:
    directories:
        - node_modules
        - ~/.yarn
        - ~/.yarn-cache
